services:
  - type: web
    name: backend-preprod
    env: node
    rootDir: backend
    region: frankfurt
    buildCommand: |
      npm install --include=dev
      npm run generate
      npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://sacsabonheurs.fr
      - key: NODE_ENV
        value: production
