services:
  - type: web
    name: backend-preprod
    env: node
    rootDir: backend
    plan: free
    region: frankfurt
    buildCommand: |
      npm install
      npm run build
      npx prisma migrate deploy
      npx prisma generate
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://sacsabonheurs.fr
      - key: NODE_ENV
        value: production
